@startuml
class Member {
email : String
}

class BoardMember {

}

class Event {
date : Date
description : String
assign(l : Location) :void

}

class Conference {
max_attendees : Integer

}

class BoardMeeting {
}

class Location {
description : String
adress : String

}

class Person {
name : String
}

class AAOUC {
newLocation(l :Location) : void
newEvent(e : Event) :void
newPerson(p :Person) :void
informEvent(e : Event) :void
registe(m : Member,(e : Event) : void
}

Event <|-- BoardMeeting
Conference --|> Event
BoardMember --|> Member: islocated in
Member --|> Person
Location"0..*"  -- "1"Event
Event"0..*"  -- "0..*" Member: attends to
Conference "0..*" -- "0..*" Person: attends to
BoardMember"0..*"  -- "0..*" BoardMeeting: attends to
AAOUC *--"0..*" Event
AAOUC *--"0..*" Location
AAOUC *-- "0..*" Person


@enduml