@startuml
class Member {

}

class BoardMember {

}

class Event {


}

class Conference {


}

class BoardMeeting {
}

class Location {


}

class Person {

}

class AAOUC {

}

Event <|-- BoardMeeting
Conference --|> Event
BoardMember --|> Member: islocated in
Member --|> Person
Location"0..*"  -- "1"Event
Event"0..*"  -- "0..*" Member: attends to
Conference "0..*" -- "0..*" Person: attends to
BoardMember"0..*"  -- "0..*" BoardMeeting: attends to
AAOUC *--"0..*" Event
AAOUC *--"0..*" Location
AAOUC *-- "0..*" Person


@enduml